version: "3.9"
services:
  eureka-server:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices
    environment:
      SPRING_PROFILES_ACTIVE:
#      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
#      - EUREKA_CLIENT_FETCH_REGISTRY=false
#      - EUREKA_SERVER_WAIT_TIME_IN_MS=5000

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - microservices
    depends_on:
      - eureka-server
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka

  account-service:
    build:
      context: ./account
      dockerfile: Dockerfile
    container_name: account-service
    ports:
      - "8081:8081"
    networks:
      - microservices
    depends_on:
      - eureka-server
      - postgres-account
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-account:5432/accountdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka

  tasks-service:
    build:
      context: ./tasks
      dockerfile: Dockerfile
    container_name: tasks-service
    ports:
      - "8082:8082"
    networks:
      - microservices
    depends_on:
      - eureka-server
      - postgres-tasks
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-tasks:5432/tasksdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka

  postgres-account:
    image: postgres:15
    container_name: postgres-account
    ports:
      - "5433:5432"
    networks:
      - microservices
    environment:
      POSTGRES_DB: accountdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - account-data:/var/lib/postgresql/data

  postgres-tasks:
    image: postgres:15
    container_name: postgres-tasks
    ports:
      - "5434:5432"
    networks:
      - microservices
    environment:
      POSTGRES_DB: tasksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - tasks-data:/var/lib/postgresql/data

networks:
  microservices:

volumes:
  account-data:
  tasks-data:
